### ISSUE TITLE
epub unzip issue

### ISSUE THREAD

**Issue by gibumkim** [readium/SDKLauncher-Android#100]
epub want to know unzip path

**Comment by gibumkim** [comment]
example
epubPath : /storage/emulated/0/epubtest/CPP0000065877.epub
spineItem:Text/cover.xhtml

cover.xhtml fullPath..??

**Comment by danielweck** [comment]
I do not understand the problem, can you please clarify?
Do you experience an application crash in SDKLauncher-Android?
Or do you have a problem in your EPUB? (e.g. missing file)

**Comment by danielweck** [comment]
No feedback, let's close this issue.

**Comment by blennerSilva** [comment]
hey guys can you help on finding the unzip path....i need to know where the lib unzips the .epub file

**Comment by danielweck** [comment]
ReadiumSDK does not unzip the entire EPUB files onto the file system. Instead, the publication resources are extracted (inflated) on the fly / in memory as needed, directly from the compressed (deflated) zip archive.
