### ISSUE TITLE
need help in Go to page

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/SDKLauncher-Android#104]
Can anyone help me please  how to add go to page functionality in readium and   It page number is showing based on chapter ,is there any way to get total number of pager from 1 to so on .
Please i would request if any one can help on this issue

**Comment by danielweck** [comment]
To avoid duplication, I would like to close this issue. Please follow-up here (or in one of the linked related issues): https://github.com/readium/readium-js/issues/16
(strictly-speaking, some of the "go to page" implementation would be in readium-shared-js, and any native code optimisation (chapter prefetching) would be in readium-sdk/Platform or any of the specific apps.
