### ISSUE TITLE
Needed help to execute SDKLauncher-Android. Troubled with one issue

### ISSUE THREAD

**Issue by Madhu-P** [readium/SDKLauncher-Android#108]
Needed help to execute SDKLauncher-Android

#### This issue is a Question

I have cloned the develop branch using git to my local. 
Using Android Studio. I have imported the SDK Launcher-Android. 
But I am getting this issue, 

"Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
Build Js Assets
1480573374699
1 Dec 2016 06:22:54 GMT
Build includes
:app:buildCssAssets UP-TO-DATE
:app:buildMultipleBundleAssets UP-TO-DATE
:app:buildSingleBundleAssets UP-TO-DATE
:app:buildAssets UP-TO-DATE
:app:buildEpubReadingSystem_Git
Build navigator.epubReadingSystem Git version info...
C:\Users\My-USER-NAME\Documents\GitHub\sdklauncher\SDKLauncher-Android\app
:app:buildEpubReadingSystem_DELETE
:app:buildEpubReadingSystem
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:prepareDebugDependencies
:epub3:copyEpub3XmlIncludes UP-TO-DATE
:epub3:copyEpub3UtilitiesIncludes UP-TO-DATE
:epub3:copyEpub3RootIncludes UP-TO-DATE
:epub3:copyEpub3Includes UP-TO-DATE
:epub3:copyGoogleUrlBaseIncludes UP-TO-DATE
:epub3:copyGoogleUrlIncludes UP-TO-DATE
:epub3:copyLibxmlIncludes UP-TO-DATE
:epub3:copyLibzipBaseIncludes UP-TO-DATE
:epub3:copySha1Includes UP-TO-DATE
:epub3:copyUtf8Includes UP-TO-DATE
:epub3:buildIncludes UP-TO-DATE
:epub3:buildMk FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':epub3:buildMk'.
> A problem occurred starting process 'command 'null/ndk-build.cmd''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED"

Please help me solve this issue. I have all the files of readium-sdk & readium-shared-js. But 
I am struck with this issue. Seems to be a dead-end.

**Comment by nakaji-dayo** [comment]
Have you installed NDK?
You can install from the SDK Manager.

**Comment by Madhu-P** [comment]
Yes. I have installed NDK. But still the problem persists.

**Comment by danielweck** [comment]
Create of edit a file called `local.properties` inside the folder:
https://github.com/readium/SDKLauncher-Android/tree/develop/SDKLauncher-Android

...and make sure these two settings are correct on your machine:
```
sdk.dir=C\:\\path\\to\\android-sdk
ndk.dir=C\:\\path\\to\\android-ndk-r13b
```

**Comment by Madhu-P** [comment]
Thank you for your quick response. Solved!
