### ISSUE TITLE
NDK makefile error with Gradle stable (feature/lcp)

### ISSUE THREAD

**Issue by fjansen** [readium/SDKLauncher-Android#113]
When I build the branch feature/lcp i've many warning and an error :
[armeabi-v7a] Compile++ thumb: lcp <= ServiceFactory.cpp

././src/main/jni/Service.cpp:35:19: fatal error: epub3.h: No such file or directory
 #include <epub3.h>

I'm on windows 10.
With the master branch, no problem i can build the project. I just comment this line in the build.gradle : 
            task.dependsOn "buildAssets",
                    ":epub3:buildMk",
                    ":lcp:buildMk"//,
                    //"buildEpubReadingSystem"

I've try to checkout the develop and master branch of "readium-lcp-client", same error for the develop branch.
Could you help me ? Thank's
Fabrice

**Comment by danielweck** [comment]
This is a known issue with Gradle "stable" (NDK makefiles), please switch to Gradle "experimental" (which will allow you to use the hybrid Java / C++ debugger from Android Studio).
To do this, simply create or edit the `local.properties` file in `./SDKLauncher-Android/SDKLauncher-Android/`, for example:
```
ndk.dir=PATH/TO/Android/sdk/ndk-bundle
sdk.dir=PATH/TO/Android/sdk
readium.ndk_experimental=true
readium.ndk_clang=false
readium.ndk_skipARM=false
readium.ndk_skipX86=false
```

**Comment by danielweck** [comment]
The branches are:
`SDKLauncher-Android` @ `feature/lcp`
`readium-sdk` @ `feature/lcp`
`readium-lcp-client` @ `develop`
`readium-shared-js` @ `develop`
`readium-shared-js/readium-cfi-js` @ `develop`

**Comment by fjansen** [comment]
Perfect, gradle succesful ! Thank's a lot Daniel

**Comment by danielweck** [comment]
Fixed
https://github.com/readium/readium-lcp-client/commit/0d672122d49379cd614d0ea3e591574e3bb466d8
