### ISSUE TITLE
Cannot render ePub contents

### ISSUE THREAD

**Issue by lmvco** [readium/SDKLauncher-Android#115]
I compiled the SDK Launcher Android (master) and then I run it in a Nexus 7 2013 edition (Android 6.0.1)

Result:
* I am able to list the epub files
* I am able to open an ePub file and see the metadata (for instance, book "Utopia" from Thomas More - https://www.epubbooks.com/book/424-utopia)
* I am not able to open book contents. The app shows an error while opening URL http://127.0.0.1:8080/chapter-003.html"

See logcat output - [logcat.txt](https://github.com/readium/SDKLauncher-Android/files/814817/logcat.txt)

**Comment by danielweck** [comment]
Could you please try again with the latest code from the `develop` branch?
https://github.com/readium/SDKLauncher-Android/tree/develop
Please use Android Studio, make sure to install / update the latest NDK v14 and other framework dependencies (AS will let you know about available automatic updates).

Remember to check your `SDKLauncher-Android/SDKLauncher-Android/local.properties` file, it should look like:
```
ndk.dir=/Users/me/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/me/Library/Android/sdk
readium.ndk_experimental=true
readium.ndk_clang=false
readium.ndk_skipARM=false
readium.ndk_skipX86=false
readium.sign_key_password=only_needed_for_release
readium.sign_store_password=only_needed_for_release
```

**Comment by lmvco** [comment]
Thanks. Now it is working.
