### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by fjansen** [readium/SDKLauncher-Android#118]
I've clone the feature/lcp branch. When i run app, i've some error messages : 

Error:Execution failed for task ':app:mergeArmDebugJniLibFolders'.
> [armeabi-v7a/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\libepub3.so	[armeabi-v7a/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\libepub3.so: Error: Duplicate resources
[armeabi-v7a/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\libgnustl_shared.so	[armeabi-v7a/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\libgnustl_shared.so: Error: Duplicate resources
[x86/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\libgnustl_shared.so	[x86/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\libgnustl_shared.so: Error: Duplicate resources
[armeabi-v7a/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\gdb.setup	[armeabi-v7a/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\gdb.setup: Error: Duplicate resources
[x86/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\libepub3.so	[x86/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\libepub3.so: Error: Duplicate resources
[x86/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\gdbserver	[x86/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\gdbserver: Error: Duplicate resources
[armeabi-v7a/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\gdbserver	[armeabi-v7a/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\gdbserver: Error: Duplicate resources
[x86/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\gdb.setup	[x86/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\gdb.setup: Error: Duplicate resources

What's wrong ?

**Comment by danielweck** [comment]
Hello, I recently updated the Gradle config, could you please try again?
Make sure to update all the submodules too:
`readium-shared-js` on `develop` branch.
`readium-lcp-client` on `develop` branch.
`readium-sdk` on `develop` branch.
`SDKLauncher-Android` on `feature/lcp` branch.

**Comment by fjansen** [comment]
I've clone again, and update with the correct brach all the submodules, and i've the same errors :

Information:Gradle tasks [:app:clean, :app:generateArmDebugSources, :app:prepareArmDebugUnitTestDependencies, :app:mockableAndroidJar, :app:generateArmDebugAndroidTestSources, :app:assembleArmDebug]
Error:Execution failed for task ':app:mergeArmDebugJniLibFolders'.
> [armeabi-v7a/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\libepub3.so	[armeabi-v7a/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\libepub3.so: Error: Duplicate resources
[armeabi-v7a/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\libgnustl_shared.so	[armeabi-v7a/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\libgnustl_shared.so: Error: Duplicate resources
[x86/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\libgnustl_shared.so	[x86/libgnustl_shared.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\libgnustl_shared.so: Error: Duplicate resources
[armeabi-v7a/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\gdb.setup	[armeabi-v7a/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\gdb.setup: Error: Duplicate resources
[x86/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\libepub3.so	[x86/libepub3.so] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\libepub3.so: Error: Duplicate resources
[x86/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\gdbserver	[x86/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\gdbserver: Error: Duplicate resources
[armeabi-v7a/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\armeabi-v7a\gdbserver	[armeabi-v7a/gdbserver] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\armeabi-v7a\gdbserver: Error: Duplicate resources
[x86/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-sdk\Platform\Android\epub3\libs\x86\gdb.setup	[x86/gdb.setup] C:\NS\Job\Nordcompo\Readium\Test_launcher_LCP\SDKLauncher-Android\readium-lcp-client\platform\android\lcp\libs\x86\gdb.setup: Error: Duplicate resources
Information:BUILD FAILED
Information:Total time: 23.8 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by johanpoirier** [comment]
Same error here:
```
Execution failed for task ':app:mergeX86ReleaseJniLibFolders'.
> [armeabi-v7a/libepub3.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/armeabi-v7a/libepub3.so	[armeabi-v7a/libepub3.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/armeabi-v7a/libepub3.so: Error: Duplicate resources
  [armeabi-v7a/libgnustl_shared.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/armeabi-v7a/libgnustl_shared.so	[armeabi-v7a/libgnustl_shared.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/armeabi-v7a/libgnustl_shared.so: Error: Duplicate resources
  [x86/libgnustl_shared.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/x86/libgnustl_shared.so	[x86/libgnustl_shared.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/x86/libgnustl_shared.so: Error: Duplicate resources
  [armeabi-v7a/gdb.setup] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/armeabi-v7a/gdb.setup	[armeabi-v7a/gdb.setup] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/armeabi-v7a/gdb.setup: Error: Duplicate resources
  [x86/libepub3.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/x86/libepub3.so	[x86/libepub3.so] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/x86/libepub3.so: Error: Duplicate resources
  [x86/gdbserver] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/x86/gdbserver	[x86/gdbserver] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/x86/gdbserver: Error: Duplicate resources
  [armeabi-v7a/gdbserver] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/armeabi-v7a/gdbserver	[armeabi-v7a/gdbserver] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/armeabi-v7a/gdbserver: Error: Duplicate resources
  [x86/gdb.setup] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/x86/gdb.setup	[x86/gdb.setup] /Users/johanpoirier/workspace/tea/SDKLauncher-Android/readium-lcp-client/platform/android/lcp/libs/x86/gdb.setup: Error: Duplicate resources
```

**Comment by llemeurfr** [comment]
@clebeaupin  is working or a simplified way to link the LCP lib as an .aar, we'll test it with @fjansen asap.

**Comment by llemeurfr** [comment]
@danielweck thinks that your issue comes from the use of Gradle "stable". It was working before, but ... You should have no more problem if you switch to Gradle "experimental" (in local.propreties)

**Comment by danielweck** [comment]
`local.properties` should contain something like (see `readium.ndk_experimental=true`):

```
ndk.dir=/Users/danielweck/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/danielweck/Library/Android/sdk
readium.ndk_experimental=true
readium.ndk_clang=false
readium.ndk_skipARM=false
readium.ndk_skipX86=false
```

**Comment by fjansen** [comment]
Build ok with "experimental" gradle.
BUT, if i try to open the lcp protected file "mantano-test-lcp.epub" i've got a error message : "LCP license problem : [ErrorCommonAlgorithMismatch} (x)"

**Comment by llemeurfr** [comment]
ok, let's move to Slack to discuss this, must be a certificate issue. 
Let's keep this issue open until the Gradle stable issue is solved.

**Comment by fjansen** [comment]
No news for build with "stable" gradle ?

**Comment by danielweck** [comment]
I am able to reproduce this issue, which at first I thought was due to a GNU STL shared vs. static configuration mismatch in the NDK Makefiles, but it turns out not to be the case (I'm looking into this).

Personally, I use Android Studio with Gradle experimental, not only because I primarily build the ReadiumSDK Android launcher app in DEBUG mode (with hybrid Java C++ debugging), but also because it works just fine in RELEASE mode. Gradle "stable" uses old legacy Makefiles, whereas Gradle "experimental" handles the nitty-gritty details behind the scenes (the user-exposed Gradle NDK DSL is more user-friendly than raw `*.mk` files).

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/SDKLauncher-Android/commit/719f7c4e769159500169e0b1e3ad4296a772da86
