### ISSUE TITLE
Suggestion needed: how to use readium project to build React Native APPs?

### ISSUE THREAD

**Issue by hz0324** [readium/SDKLauncher-Android#120]
I am trying to build an ebook reading app for iOS and Android.
Since I am a web front-end developer, I would like to use React Native (https://facebook.github.io/react-native/) to build my app. 

I have used readium-js-viewer before to build an web app, so I know how readium works on web.
But I am confused about which project should I use for the App, specifically when I am using React Native.

Now, I think I can webview inside iOS and Android to build a Web app that runing on the phone. In this case, I can still use readium-js-viewer project as a reference. But as you can tell, the user experience will be really bad. So I need some suggestions about building a better app using readium.

Please help me,  how to use readium project to develop a Native App if I use React Native in the project?
Thank you very much.

**Comment by danielweck** [comment]
I am closing this issue in favour of this discussion: https://github.com/readium/readium-js-viewer/issues/628#issuecomment-315732823
