### ISSUE TITLE
Footnotes links not working in Webview version 59.0.3071.125

### ISSUE THREAD

**Issue by nimisis** [readium/SDKLauncher-Android#121]
Related to 

https://github.com/readium/SDKLauncher-iOS/issues/93

and using the same epub ("James") listed there, the footnotes links were navigating correctly back and forth as recently as Webview version 58.0.3029.83 on Android devices and emulator but no longer in version 59.0.3071.125.

**Comment by rkwright** [comment]
Can you provide some more details?   What application are you seeing this in? Are there any errors in the log or console output.  Note that we have recently integrated a number of CFI fixes into the develop branch in readium-shared-js.  Can you test against that?

**Comment by nimisis** [comment]
Thanks for getting back to me. Sure, if you run the latest version of SDKLauncher-Android with Webview 59.0.3071.125 on your device, and open James.epub (available via the link above), then pretty much every footnote there does not navigate to where it should. Sadly this is still the case even with the new commits on develop branch in readium-shared-js.

**Comment by danielweck** [comment]
Let's continue the discussion here please:
https://github.com/readium/readium-shared-js/issues/398#issuecomment-333285873
