### ISSUE TITLE
Android NDK: Aborting    .  Stop.

### ISSUE THREAD

**Issue by marzic93** [readium/SDKLauncher-Android#123]
Hi! I can't build project. When i run app, i've some error messages :

Error:(115) *** Android NDK: Aborting    .  Stop.

Error:Execution failed for task ':epub3:buildMk'.
> Process 'command 'C:\Users\marzic\AppData\Local\Android\Sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

**Comment by danielweck** [comment]
Hello, what is the NDK version? Do you use Android Studio, or do you invoke the Gradle build from the command line? Have you tried activating the non-stable Gradle version, which supports better NDK integration? (add readium.ndk_experimental in local.properties) https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/build.gradle#L29

**Comment by BrunoAndroidDev** [comment]
Hello!
Same here. I've activated the experimental version as @danielweck said and it's ok now.

**Comment by xiaoxiaomuou** [comment]
Hello, I have encountered the same translation compiler, how can you give specific advice?

**Comment by danielweck** [comment]
For your information, I have just upgraded versions in the build scripts (to match the Android Studio auto-updates):

https://github.com/readium/SDKLauncher-Android/commit/d8c7c44baa48bb17a73d3e5c3d3b6e25c73225b2

https://github.com/readium/readium-sdk/commit/e9e89aaeaaa4e49ab85c5238d20efb615e3bdc41

https://github.com/readium/readium-lcp-client/commit/40e53ad3c1435cb80a596387bab15cd7ef4c95bd

... and I have successfully built (NDK 15 GCC, not Clang) and launched (i.e. debugged in dual Java / C++ mode) the ReadiumSDK launcher app on my Android phone (ARM device, Oreo API-26).

`local.properties`
```
ndk.dir=/Users/danielweck/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/danielweck/Library/Android/sdk
readium.ndk_experimental=true
readium.ndk_clang=false
readium.ndk_skipARM=false
readium.ndk_skipX86=true
```

**Comment by danielweck** [comment]
Note that with `readium.ndk_experimental=false` in `local.properties`, I had to downgrade `APP_PLATFORM` to `android-19` as the latest NDK(s) do not support `android-25`:

https://developer.android.com/ndk/guides/stable_apis.html

https://github.com/readium/readium-sdk/commit/965fbb666c27ef76462dbfb379abb7c4e4015b5a

**Comment by blennerSilva** [comment]
guy im sorry but im still not able to compile the sample code im using NDK 15.2.
What im doing is clicking on . de SDK LAUNCHER with the gradle logo and gives me this erro

**Comment by danielweck** [comment]
@blennerSilva see https://github.com/readium/SDKLauncher-Android/issues/125
please try NDK 14.
