### ISSUE TITLE
Compiler highlights plug-in, do note to synchronize the question to ask? More anxious, please help, thank you

### ISSUE THREAD

**Issue by xiaoxiaomuou** [readium/SDKLauncher-Android#129]
I would like to give up the hypothesis in the android program, I would like to highlight the effective entry, to take notes and try and web-side synchronization test, may I ask someone can help me? Tell me how to do it? Thank you very much!

**Comment by danielweck** [comment]
The default build of `readium-shared-js` includes the Hypothesis plugin, but you can easily deactivate it by commenting this line:
https://github.com/readium/readium-shared-js/blob/62490d18031c6dd675639b442a7b791274bfe7b1/plugins/plugins.cson#L6
...then simply build your own version of `readium-shared-js`, by following the instructions:
https://github.com/readium/readium-shared-js/blob/develop/README.md#prerequisites

You can of course re-activate the old "highlight" plugin:
https://github.com/readium/readium-shared-js/blob/62490d18031c6dd675639b442a7b791274bfe7b1/plugins/plugins.cson#L3
...but this will only help you create document highlights, you will have to write your own logic for managing annotations, etc.
