### ISSUE TITLE
problem on integrating readium

### ISSUE THREAD

**Issue by blennerSilva** [readium/SDKLauncher-Android#130]
Hey guys i know there is something similar to my question already, but i am having so much trouble on integrating readium on android.. i followed the doc you guy provided on how to make de module but i just cant get it to work ir generates this error.

Error:Execution failed for task ':epub3:buildMk'. > Process 'command '/Users/blennersilva/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

could guys please help or make an easier documentation to follow (sorry if im being inconvenient)

**Comment by danielweck** [comment]
please see:
https://github.com/readium/SDKLauncher-Android/issues/123#issuecomment-332799972
