### ISSUE TITLE
generating libepub3.so(64 bit) for arm64-v8a 

### ISSUE THREAD

**Issue by adnanali-indpro** [readium/SDKLauncher-Android#134]
#### Steps to reproduce
1. First, added ABI_APP for v8a but not working

ERRO getting :    Error:error: conflicting declaration 'typedef long long unsigned int uint64_t'

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-sdk/issues/245
Can you please report back on the original conversation thread? Many thanks!
