### ISSUE TITLE
Unable to load the epub List.

### ISSUE THREAD

**Issue by abhi08singh** [readium/SDKLauncher-Android#139]
I am able to configure the Project Successfully. 
but running application on real device I didn't get any Epub List.

I have also read the various link in issues section.
[https://github.com/readium/SDKLauncher-Android/issues/98#issuecomment-231199794](url)

but it does not resolve the issues. 

Every time I got the same Toast. 
"No eBooks Found: /storage/emulated/0/sdcard0/epubtest"

Please help me out

**Comment by danielweck** [comment]
does the 'epubtest' folder exist on your "sdcard" (Android internal storage)

**Comment by abhi08singh** [comment]
Yes ,

Even I have paste a EPUB also in the same folder.

**Comment by abhi08singh** [comment]
Yes,

I have paste the EPUB file also to the same folder.

**Comment by danielweck** [comment]
hardware device or software emulator?
either way, what do you see in the folder when you use ADB?
'adb shell ls -als /sdcard'

**Comment by abhi08singh** [comment]
I am using real device to Debug

**Comment by abhi08singh** [comment]
I have done it by re-cloning the Same Version may be there is issue with the previously cloned Repo.

Thanks Guys
