### ISSUE TITLE
TTS is not working

### ISSUE THREAD

**Issue by Krishna-Vyas** [readium/SDKLauncher-Android#155]
I have successfully loaded all modules, like main, readium-shared-js, Epub3. 
And thanks to you, Media Overlay is running perfectly.
But TTS is not working as expected.

I need to play TTS if media overlay is not present in ePUB. I think TTS feature is implemented slightly, but it's not in the working stage.
Can anyone say, what changes required to make TTS work?

**Comment by danielweck** [comment]
I wasn’t aware that synthetic speech readaloud was implemented in this project. On Android, I assume the TalkBack screen reader can access the publication content (i.e. HTML documents) hosted inside Readium’s iframe, but of course a stand-alone TTS feature implemented specifically by Readium would offer a different UX.

PS: I am pleasantly surprised to hear that EPUB Media Overlays still work, as the code hasn’t evolved for a long time. Well done for putting together a working app! :)

**Comment by danielweck** [comment]
Closing as N/A Not Applicable (as TTS is not implemented in this SDK)

**Comment by Krishna-Vyas** [comment]
Okay. Thank you.
