### ISSUE TITLE
Embedded videos are not played

### ISSUE THREAD

**Issue by Twibit** [readium/SDKLauncher-Android#19]
Hi,

I tried to read [cc-shared-culture-20120130.epub](https://epub-samples.googlecode.com/files/cc-shared-culture-20120130.epub) but none of the embedded videos are played.

```
Package.nativeGetArchiveInfoSize(): no archive found for path 'OEBPS/video/shared-culture.mp4'
Package.nativeReadStreamForRelativePath(): no archive found for path 'OEBPS/video/shared-culture.mp4'
```

Branch : develop
Lastest commit : [7f964be716eb5e34d9ae63278f890f545b1a3c18](https://github.com/readium/SDKLauncher-Android/tree/7f964be716eb5e34d9ae63278f890f545b1a3c18)
Android version : 4.4.2

**Comment by danielweck** [comment]
Addressed by #50
