### ISSUE TITLE
Some images are truncated / not fully loaded

### ISSUE THREAD

**Issue by Twibit** [readium/SDKLauncher-Android#22]
Hello,

It happens that some images in an epub are not fully loaded and not displayed correctly.
I saw it multiple times and not always on the same image/epub. 

Here is an example : 
![Screenshot](http://files.twibit.com/file/image/2B/export.jpeg)

**Comment by danielweck** [comment]
Can this issue be reproduced with the latest code?

**Comment by danielweck** [comment]
This is fixed in:
https://github.com/readium/SDKLauncher-Android/tree/feature/epubServerAndroidAsync
(not able to reproduce any media loading issues)

**Comment by danielweck** [comment]
Was fixed in #50
