### ISSUE TITLE
Inconsistent tabs/spaces in code base.

### ISSUE THREAD

**Issue by JCCR** [readium/SDKLauncher-Android#41]
The project seems to have started with tabs as the code indent style. Over time code with 4 spaces as indentation has been introduced into the code base (I'm guilty of this too if you can tell from my latest PRs)

What should we do about this?

- Enforce tabs as the project's indentation style, while fixing up all other inconsistencies?
- Switch everything to use spaces?

(I don't mean to start a holy war here..)

**Comment by rkwright** [comment]
Long since resolved to be 4 spaces, not tabs.  Closing
