### ISSUE TITLE
64 bit support? (AArch64 armv8a libs, with NDK r10c + toolchain 4.9)

### ISSUE THREAD

**Issue by danielweck** [readium/SDKLauncher-Android#46]
I wonder whether the configuration build files Application.mk, Android.mk, ndk-compile.sh are setup correctly to support 64 bit hardware (Nexus 9, etc.?).
Lots of useful info here:
https://groups.google.com/forum/#!forum/android-ndk

**Comment by danielweck** [comment]
related (x86 successfull build): https://github.com/readium/readium-sdk/pull/99/files

**Comment by msintov** [comment]
Daniel, do you know what work is remaining to support 64-bit Android hardware (i.e., Nexus 6 and Nexus 9)? I have not yet tried to build the library myself. Are there known issues?

Here is a link with some info:
http://android-developers.blogspot.com/2014/10/getting-your-apps-ready-for-nexus-6-and.html

Thanks!

**Comment by danielweck** [comment]
I am successfully running armv7 builds of the Android Readium SDK "launcher" app on my Nexus 6P, but that's not 'proper' 64bit support though. I don't know much about the state of AArch64 armv8a, and whether or not a project like Readium SDK would actually benefit from transitioning (performance, memory implications?). Thoughts?

**Comment by msintov** [comment]
Interesting. With my Nexus 9, I get an error about a missing arm64-v8a library when I try to use the Readium library.

I am curious what your APP_ABI is set to? Is it just armeabi-v7a?

Thank you!

**Comment by danielweck** [comment]
Yes, just arm v7 (so I am probably not hitting the v8 / 64bit bug)

**Comment by clebeaupin** [comment]
We do not have a nexus 9 device. Could you try to add arm64-v8a in Application.mk (readium sdk) 
APP_ABI := armeabi-v7a x86
