### ISSUE TITLE
host_app_feedback.js inconsistent with other platforms (outdated?)

### ISSUE THREAD

**Issue by JCCR** [readium/SDKLauncher-Android#49]
The host_app_feedback.js included with the launcher is inconsistent with the one in the iOS/OSX launchers.

For example:

It includes a hook into ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED (the others do not) and the handler is missing the right callback signature:
this.onContentLoaded = function() {

should be something like
this.onContentLoaded = function($iframe, spineItem) {

**Comment by danielweck** [comment]
Thanks @JCCR !
I agree about cleaning-up.
Currently though, this is only used to print a debug message, so the parameters are unused:

```
@JavascriptInterface
public void onContentLoaded() {
if (!quiet)
Log.d(TAG, "onContentLoaded");
}
```

https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/src/org/readium/sdk/android/launcher/WebViewActivity.java#L751

To compare:

SDKLauncher-Android:
https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/assets/readium-shared-js/host_app_feedback.js#L75

SDKLauncher-OSX:
https://github.com/readium/SDKLauncher-OSX/blob/develop/LauncherOSX/ReaderScripts/host_app_feedback.js#L82

SDKLauncher-iOS:
https://github.com/readium/SDKLauncher-iOS/blob/develop/Resources/host_app_feedback.js#L81

SDKLauncher-Windows:
https://github.com/readium/SDKLauncher-Windows/blob/feature/feature_revised_launcher/SDKLauncher-Win/ReaderScripts/host_app_feedback.js#L24

**Comment by danielweck** [comment]
Note that this will be addressed when we merge the feature/plugins branch to develop:
https://github.com/readium/SDKLauncher-Android/blob/feature/plugins/SDKLauncher-Android/assets/readium-shared-js/host_app_feedback.js

**Comment by rkwright** [comment]
Need to review this now that the restructuring and plugins work has been merged.

**Comment by danielweck** [comment]
As expressed in the above comment ( https://github.com/readium/SDKLauncher-Android/issues/49#issuecomment-71539027 ), the `CONTENT_DOCUMENT_LOADED` Readium event is not actually used for anything other than a debug message in SDKLauncher-Android. Other than that, the `host_app_feedback.js` has been revamped significantly since the RequireJS / Plugins merge to the develop branch. I suggest we close this issue now.
