### ISSUE TITLE
i have a question about shared-js between ver 0.10 and 0.15

### ISSUE THREAD

**Issue by yuch1001** [readium/SDKLauncher-Android#53]
when i test in mfc, in repository of mfc develop, i saw news that js's version change 0.10 to 0.15.

so i change js's version too, to 0.15.

i have a test epub, readium provide and make by calibre(in calibre case, use scanned comicbook. html have a only image source).

and open epub.

in 0.10, comicbook image is good. but accessible_epub is not good. occur http error( with these )

![error](https://cloud.githubusercontent.com/assets/2336657/6145198/99c5cee4-b222-11e4-8173-bc5b0df693fb.png)

almost ERROR_CONNECTION_INVALID.

and in 0.15, accessible_epub is good! very. but comicbook image is not good.

next images is captured image.

[this is using 0.10]
![ver010image](https://cloud.githubusercontent.com/assets/2336657/6145256/3078bee6-b223-11e4-9eef-005653f2ffbf.png)

[this is using 0.15]
![ver015image](https://cloud.githubusercontent.com/assets/2336657/6145258/386b66d0-b223-11e4-9e01-1391a799a55d.png)

this html is good in chrome browser and ie.

is there big difference between 0.10 and 0.15 with image viewing?

and css is not available in epub?

thank you!

**Comment by danielweck** [comment]
moved to the windows launcher app repo:
https://github.com/readium/SDKLauncher-Windows/issues/23
