### ISSUE TITLE
Total Page Count 

### ISSUE THREAD

**Issue by finneapps** [readium/SDKLauncher-Android#64]
Have you done any thoughts on how to calculate the total count of pages in a book?
One solution would be to add a hidden Fragment that loads each chapter the same way as a you normal would, and then get the chapter page count for each chapter. Or is there a better way?

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-js/issues/16

**Comment by rkwright** [comment]
Closing as a duplicate of readium/readium-js#16
