### ISSUE TITLE
note and highlight

### ISSUE THREAD

**Issue by membrown** [readium/SDKLauncher-Android#67]
please help.
how can I add highlight and note to android readium ?

**Comment by danielweck** [comment]
Readium currently includes a highlighting feature, but there is no support for proper annotations yet (notes attached to selection highlights).

See `addSelectionHighlight` in `EpubAnnotationsModule`:
https://github.com/readium/readium-shared-js/blob/develop/lib/annotations_module.js#L709

Note that soon a new plugins architecture will be merged from a feature branch into the develop branch. This will somewhat simplify the API, see for example:
https://github.com/readium/readium-js/blob/feature/pluginsX/dev/index.js#L109

```javascript
ReadiumSDK.on(ReadiumSDK.Events.PLUGINS_LOADED, function(reader) {

                // readium built-in (should have been require()'d outside this scope)
                console.log(reader.plugins.annotations);
                reader.plugins.annotations.initialize({annotationCSSUrl: readerOptions.annotationCSSUrl});
                reader.plugins.annotations.on("annotationClicked", function(type, idref, cfi, id) {
                    console.log("ANNOTATION CLICK: " + id);
                    reader.plugins.annotations.removeHighlight(id);
                });
                reader.plugins.annotations.on("textSelectionEvent", function() {
                    console.log("ANNOTATION SELECT");
                    reader.plugins.annotations.addSelectionHighlight(Math.floor((Math.random()*1000000)), "highlight");
                });

            });
```

**Comment by rudra0713** [comment]
Hi Daniel,
   I was wondering how to get the idref and cfi when text-selection-event occurs ? I was trying the store the cfi once the user highlights any text in epub ? But I anot sure how to get the cfi of the user selected text ?

**Comment by danielweck** [comment]
@rudra0713 You could follow the example with the `highlights` plugin:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L797
```javascript
var selection = readium.reader.plugins.highlights.addSelectionHighlight(tempId, "temp-highlight");
var cfi = selection.contentCFI;
`

**Comment by danielweck** [comment]
Also, `readium.reader.bookmarkCurrentPage()` returns a "bookmark" object that contains the `idref` property (spine item reference).
See:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L787

**Comment by danielweck** [comment]
The relevant code in the `highlights` plugin is `getCurrentSelectionCFI()`:
https://github.com/readium/readium-shared-js/blob/develop/plugins/highlights/controller.js#L217

**Comment by rudra0713** [comment]
Great help. Thank you very much @danielweck .
