### ISSUE TITLE
How to get dc:publisher ?

### ISSUE THREAD

**Issue by romaingiard** [readium/SDKLauncher-Android#77]
Hello,

Is-it possible to get dc:publisher in the EPub, it seems that the tag is not loaded in objet Package (Package.java) .

Thanks for help.

**Comment by romaingiard** [comment]
Can I dot-it by myelf ? or may I wait for a new release of Android-Launcher ?

**Comment by rkwright** [comment]
@romaingiard We would welcome a pull-request for this (against develop, please).

**Comment by rkwright** [comment]
@romaingiard  As it turns out, someone has already done this work, they just hadn't pushed it back to the repo yet.  They will create a PR shortly (this week?) and we will merge it into develop.

**Comment by romaingiard** [comment]
Ok I found the mantano branch which propose this feature.
