### ISSUE TITLE
Generate CFI from html in Java

### ISSUE THREAD

**Issue by romaingiard** [readium/SDKLauncher-Android#78]
Hello,

Is it possible to generate CFI in java ? I want to develop a search function for epubs in Android Side (the html/xhtml content are in a SQL Lite FTS table), generate CFI for results and highlights results found.
- I've seen in SDK a class CFI.java which is empty.

Thank you for your help.

**Comment by danielweck** [comment]
There is some native C++ code in ReadiumSDK, but you would need to write JNI wrappers yourself I am afraid.

Note that the Javascript Readium implementation of CFI is actively used ( https://github.com/readium/readium-cfi-js + https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js ), but I am not so sure about the status / usage / relevance of the C++ implementation.

Useful references:

Unit tests:
https://github.com/readium/readium-sdk/blob/develop/UnitTests/cfi_tests.cpp

CFI class:
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/cfi.h
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/cfi.cpp

CFI resolver:
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/cfi-resolver.js
