### ISSUE TITLE
Unable to build feature/gradle-experimental branch

### ISSUE THREAD

**Issue by msintov** [readium/SDKLauncher-Android#86]
I have SDKLauncher-Android sync'ed to tip with no local changes (latest code change is Mar 11, 2016). I am using Android Studio 2.0. I get 1 error when I try to build:

Execution failed for task ':app:buildEpubReadingSystem_Git_TAG_ANDROID'.
> Process 'command 'git'' finished with non-zero exit value 128

Any tips to get around that? Thank you!

**Comment by danielweck** [comment]
Hello please comment out the epubReadingSystem build task in the app's Gradle. We need to figure out why git fails too :(

**Comment by fredrod** [comment]
I've been able to build it by commenting the task out, but I can't get it to link since the warnings as errors is enabled. I've tried to disable it with : "LOCAL_LDFLAGS := -Wl,--no-fatal-warnings" in the Experimental.mk and Stable.mk but it didn't worked.

Any idea why I can't disable it? Thanks !

**Comment by fredrod** [comment]
I've been able to disable the ld warnings as errors with : LOCAL_DISABLE_FATAL_LINKER_WARNINGS := true

source: http://stackoverflow.com/questions/35950410/ndk-11-is-treating-warnings-as-errors

**Comment by danielweck** [comment]
Thanks for the `LOCAL_DISABLE_FATAL_LINKER_WARNINGS := true` tip. We will discuss merging the feature branch soon, so this is timetly.

**Comment by clebeaupin** [comment]
I have fixed it in gradle-experimental branch

**Comment by danielweck** [comment]
As @clebeaupin  said, fix pushed here: https://github.com/readium/readium-sdk/commit/d4d7abf6d99a8834554b2e6731b427f177f68f87

**Comment by danielweck** [comment]
@msintov the epubReadingSystemTask should now work fine. Closing.
