### ISSUE TITLE
Gradle Maven lib dependencies (AndroidAsync, etc.)

### ISSUE THREAD

**Issue by danielweck** [readium/SDKLauncher-Android#88]
Currently not in feature/gradle-experimental:
https://github.com/readium/SDKLauncher-Android/blob/feature/gradle-experimental/SDKLauncher-Android/app/build.gradle#L9

...but in feature/lcp:
https://github.com/readium/SDKLauncher-Android/blob/feature/lcp/SDKLauncher-Android/app/build.gradle#L9

```gradle
dependencies {
    compile 'com.android.support:support-v4:23.+'
    compile 'com.koushikdutta.ion:ion:2.+'
    compile 'commons-io:commons-io:2.4'
}
```

TODO:

https://github.com/koush/AndroidAsync
```gradle
dependencies {
    compile 'com.koushikdutta.async:androidasync:2.+'
}
```
...to replace https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/libs/androidasync-2.0.1.jar

**Comment by clebeaupin** [comment]
AndroidAsync is a dependency of ion. It's why I have omitted to mention it in the build.gradle

**Comment by danielweck** [comment]
Great! Let's leave this issue open as the Gradle-Maven dependencies are not in the develop branch yet.

**Comment by danielweck** [comment]
Also, let's make it clear in the Gradle script:

```gradle
dependencies {
    compile 'com.android.support:support-v4:23.+'
    compile 'com.koushikdutta.ion:ion:2.+'
    // compile 'com.koushikdutta.async:androidasync:2.+' ALREADY INCLUDED AS DEP OF com.koushikdutta.ion
    compile 'commons-io:commons-io:2.4'
}
```

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/SDKLauncher-Android/commit/852704fa66a338b7365062024e3a064a551ba3bd
