### ISSUE TITLE
CPUCacheUtils arm64-v8a (android 64 bit)

### ISSUE THREAD

**Issue by naveenrajproject** [readium/SDKLauncher-Android#96]
I have generated all required libraries for ThirdParty dependencies for android 64 bit (arm64-v8a, x86_64 architecture). But while creating *.so files using command
 ./ndk-compile.sh build "NDK Path" 
then below error occured.
../../readium-sdk/Platform/Android/obj/local/arm64-v8a/objs/epub3/ePub3/utilities/CPUCacheUtils.o: In function `epub_sys_cache_control':

../../readium-sdk/Platform/Android/./../../ePub3/utilities/CPUCacheUtils.c:31: undefined reference to `epub_sys_cache_flush'

../../readium-sdk/Platform/Android/./../../ePub3/utilities/CPUCacheUtils.c:28: undefined reference to `epub_sys_cache_invalidate'

collect2: error: ld returned 1 exit status

As of now, I din't found CPUCacheUtils files for 64 bit support. 

So Any help will be appreciated to provide support CPUCacheUtils for 64 bit on arm & x86_64 architecture.

**Comment by rkwright** [comment]
To be clear, you are using the develop branch?  We have now switched to Android Studio 2.1 and abandoned Eclipse. We should all be using AS 2.1.  What platform are you developing on? What version?

**Comment by naveenrajproject** [comment]
I am using Master branch. Host Machine: Mac OS x EI Capitan(10.11.1). 
NDK version: android-ndk-r11c-darwin-x86_64 
Trying to generate *.so files and then use those in Android Studio(in jniLibs folder).
Unable to run readium on Google Nexus 5x or 6p, Nexus 5x is using 
CPU‎: ‎1.8 GHz hexa core 64-bit ARMv8-A.

**Comment by danielweck** [comment]
Please use the `develop` branch. Google deprecated Eclipse support, they now recommend Android Studio.
I personally use a 64 bit device, but I only compile for ARMv7 and x86. See:
https://github.com/readium/SDKLauncher-Android/issues/46

**Comment by naveenrajproject** [comment]
could you please provide steps/references to build it using android studio 2.x onwards ?

**Comment by rkwright** [comment]
@naveenrajproject Please see 

https://github.com/readium/SDKLauncher-Android/tree/develop

**Comment by naveenrajproject** [comment]
Thank you, I am able to run Readium(dev branch) on Android 64 bit (Nexus 5x) as stand alone project using Android studio - using only armeabi-v7a (libepub3.so) & x86 (libepub3.so). 

But now I have a project which has dependencies on Realm(0.87.4), Fresco, amazon sdk libraries etc...
After integration of Readium Module in my project, getting the below error.
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/..../base.apk"], nativeLibraryDirectories=[/data/app/..../lib/arm64, /data/app/.../lib/arm64-v8a, /vendor/lib64, /system/lib64]]]  couldn't find "libepub3.so"

After analyzing the apk (by unzipped), these (arm64-v8a, x86_64) directories have been created in lib and it has librealm-jni.so file, I think Realm has Jni lib for 32 and 64 bits. libepub3.so is not available (as we have not provided for 64 bit (arm64-v8a) actually). 
libepub3.so is only found in armeabi-v7 and x86 directories of my apk. 

So is there any way to tell the device to load libepub3.so file from armeabi-v7a ??

**Comment by danielweck** [comment]
Support for 64-bits ARM is currently missing. You can give a try by modifying the build settings:
https://github.com/readium/readium-sdk/blob/develop/Platform/Android/epub3/Application.mk#L1
`APP_ABI := armeabi-v7a x86`
...but as @clebeaupin remarked, there are missing 64-bits dependencies so you would have to troubleshoot this as well.
https://github.com/readium/readium-sdk/blob/develop/Platform/Android/epub3/build_experimental.gradle#L54
```gradle
    android.productFlavors {
        create ("arm") {
            ndk.with {
                abiFilters.add("armeabi-v7a")
                ldFlags.addAll([
                        "-L${file("./obj/local/armeabi-v7a")}".toString(),
                        "-L${file("../../../ePub3/ThirdParty/openssl-android/lib/armeabi-v7a")}".toString(),
                        "-L${file("../../../ePub3/ThirdParty/icu4c/lib/armeabi-v7a")}".toString()
                ])
            }
        }
        create("x86") {
            ndk.with {
                abiFilters.add("x86")
                ldFlags.addAll([
                        "-L${file("./obj/local/x86")}".toString(),
                        "-L${file("../../../ePub3/ThirdParty/openssl-android/lib/x86")}".toString(),
                        "-L${file("../../../ePub3/ThirdParty/icu4c/lib/x86")}".toString()
                ])
            }
        }
    }
```

**Comment by danielweck** [comment]
PS: please take a look at the README references to see how to compile the static libs for the Unicode and SSL libraries:

https://github.com/readium/readium-sdk/blob/develop/ePub3/ThirdParty/icu4c/lib/README.md

https://github.com/readium/readium-sdk/blob/develop/ePub3/ThirdParty/openssl-android/lib/README.md

**Comment by danielweck** [comment]
I have started a new "thread" to discuss ARM64:
https://github.com/readium/readium-sdk/issues/245
