### ISSUE TITLE
readium-lcp-client project?

### ISSUE THREAD

**Issue by gibumkim** [readium/SDKLauncher-Android#97]
readium-lcp-client download link please

**Comment by gibumkim** [comment]
complet..

build_epubReadingSystem.gradle 

file edit

def getCommandOutput(cwd, cmd) {
    def stdout = new ByteArrayOutputStream()
    return stdout.toString().trim()
}

AND

android SDK,NDK,GIT The exact settings required confirmation

**Comment by danielweck** [comment]
This is currently a private repository:
https://github.com/readium/readium-lcp-client

It is referenced from this feature branch, which is work-in-progress:
https://github.com/readium/SDKLauncher-Android/tree/feature/lcp

**Comment by rkwright** [comment]
@gibumkim   Can you please clarify who you are, your interest and affiliation?

Thanks Ric Wright, Director of Engineering, Readium Foundation
